/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sma;

import Componentes.NXT.Dispositivos;
import Componentes.NXT.Robot;
import Componentes.Pizarra.Pizarra;
import Networking.ConexionACO;
import Networking.ConexionVisionArtificial;
import Networking.base.Puertos;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author diego_juliao
 */
public class index extends javax.swing.JFrame 
{    
    private final ConexionVisionArtificial conect_VA;
    private ConexionACO conect_ACO;
    
    private final Robot romer,greta,fryda;
    private int robotsConected;
    
    public static Pizarra p;

    /**
     * Creates new form index
     */
    public index() 
    {
        initComponents();
        
        JButton buttonsStartRobots[] = { jButton_EmpFryda, jButton_EmpGreta, jButton_EmpRomer };
        
        conect_VA = new ConexionVisionArtificial( jLabel_connect_VA, buttonsStartRobots );
        
        greta = new Robot( Dispositivos.Greta, 3, conect_ACO, jLabel_dirGreta, conect_VA );
        romer = new Robot( Dispositivos.Romer, 2, conect_ACO, jLabel_dirRomer, conect_VA );
        fryda = new Robot( Dispositivos.Frida, 1, conect_ACO, jLabel_dirFryda, conect_VA );
        
        p= new Pizarra(fryda, greta, romer);
        
        robotsConected = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Panel_Agentes3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_connect_romer = new javax.swing.JLabel();
        jButton_conectarRomer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_connect_frida = new javax.swing.JLabel();
        jButton_conectarFrida = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_connect_greta = new javax.swing.JLabel();
        jButton_conectarGreta = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_calibrarSensoresOpticos = new javax.swing.JLabel();
        jButton_CalibrarSensoresRobot = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_ACO_estado = new javax.swing.JLabel();
        jButton_ACO_Connect = new javax.swing.JButton();
        jTextfield_ACO_host = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel_connect_VA = new javax.swing.JLabel();
        Panel_Agentes4 = new javax.swing.JPanel();
        Panel_Agentes5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_EmpFryda = new javax.swing.JButton();
        jButton_ControlFryda = new javax.swing.JButton();
        jLabel_dirFryda = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel42 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel43 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        Panel_Agentes6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_EmpGreta = new javax.swing.JButton();
        jButton_ControlGreta = new javax.swing.JButton();
        jLabel_dirGreta = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel46 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel47 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        Panel_Agentes7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_EmpRomer = new javax.swing.JButton();
        jButton_ControlRomer = new javax.swing.JButton();
        jLabel_dirRomer = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel50 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel51 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Droid Sans Mono", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SMA");
        Titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Panel_Agentes3.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tareas Pendientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes3.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes3.setPreferredSize(new java.awt.Dimension(666, 666));

        jLabel1.setText("Conectar Romer");

        jLabel_connect_romer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarRomer.setText("Go");
        jButton_conectarRomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarRomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_conectarRomer)
                .addGap(6, 6, 6)
                .addComponent(jLabel_connect_romer)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_romer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarRomer))))
        );

        jLabel5.setText("Conectar Frida");

        jLabel_connect_frida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarFrida.setText("Go");
        jButton_conectarFrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarFridaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_conectarFrida)
                .addGap(6, 6, 6)
                .addComponent(jLabel_connect_frida)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_frida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarFrida))))
        );

        jLabel7.setText("Conectar Greta");

        jLabel_connect_greta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarGreta.setText("Go");
        jButton_conectarGreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarGretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_conectarGreta)
                .addGap(6, 6, 6)
                .addComponent(jLabel_connect_greta)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_greta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarGreta))))
        );

        jLabel13.setText("Calibrar Sensores Opticos");

        jLabel_calibrarSensoresOpticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_CalibrarSensoresRobot.setText("Go");
        jButton_CalibrarSensoresRobot.setEnabled(false);
        jButton_CalibrarSensoresRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalibrarSensoresRobotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CalibrarSensoresRobot)
                .addGap(6, 6, 6)
                .addComponent(jLabel_calibrarSensoresOpticos)
                .addGap(0, 0, 0))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel_calibrarSensoresOpticos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_CalibrarSensoresRobot))))
        );

        jLabel19.setText("Conectar ACO");

        jLabel_ACO_estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_ACO_Connect.setText("Go");
        jButton_ACO_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ACO_ConnectActionPerformed(evt);
            }
        });

        jTextfield_ACO_host.setText("127.0.0.1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextfield_ACO_host, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ACO_Connect)
                .addGap(6, 6, 6)
                .addComponent(jLabel_ACO_estado)
                .addGap(0, 0, 0))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel_ACO_estado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ACO_Connect)
                        .addComponent(jTextfield_ACO_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel21.setText("Conectar Vision Artificial");

        jLabel_connect_VA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/connecting25x25.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(jLabel_connect_VA)
                .addGap(0, 0, 0))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_connect_VA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_Agentes3Layout = new javax.swing.GroupLayout(Panel_Agentes3);
        Panel_Agentes3.setLayout(Panel_Agentes3Layout);
        Panel_Agentes3Layout.setHorizontalGroup(
            Panel_Agentes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Agentes3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Agentes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_Agentes3Layout.setVerticalGroup(
            Panel_Agentes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Agentes3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Agentes4.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agentes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes4.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes4.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes4.setLayout(new javax.swing.BoxLayout(Panel_Agentes4, javax.swing.BoxLayout.PAGE_AXIS));

        Panel_Agentes5.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fryda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes5.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes5.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes5.setLayout(new javax.swing.BoxLayout(Panel_Agentes5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpFryda.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpFryda.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpFryda.setText("Empezar");
        jButton_EmpFryda.setEnabled(false);
        jButton_EmpFryda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpFrydaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EmpFryda);

        jButton_ControlFryda.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlFryda.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlFryda.setText("Simple Contol");
        jButton_ControlFryda.setEnabled(false);
        jButton_ControlFryda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlFrydaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlFrydaKeyReleased(evt);
            }
        });
        jPanel1.add(jButton_ControlFryda);

        Panel_Agentes5.add(jPanel1);

        jLabel_dirFryda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirFryda.setEnabled(false);
        jLabel_dirFryda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirFrydaMouseClicked(evt);
            }
        });
        Panel_Agentes5.add(jLabel_dirFryda);

        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensor Óptico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel40.setLayout(new javax.swing.BoxLayout(jPanel40, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel41.setBackground(new java.awt.Color(197, 197, 197));

        jLabel69.setText("Nada");

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel70)
                .addGap(0, 0, 0))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel41);
        jPanel40.add(filler1);

        jPanel42.setBackground(new java.awt.Color(197, 197, 197));

        jLabel65.setText("Obstáculo");

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel66)
                .addGap(0, 0, 0))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel42);
        jPanel40.add(filler2);

        jPanel43.setBackground(new java.awt.Color(197, 197, 197));

        jLabel67.setText("Agente");

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel68)
                .addGap(0, 0, 0))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel43);

        Panel_Agentes5.add(jPanel40);

        Panel_Agentes4.add(Panel_Agentes5);

        Panel_Agentes6.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Greta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes6.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes6.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes6.setLayout(new javax.swing.BoxLayout(Panel_Agentes6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpGreta.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpGreta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpGreta.setText("Empezar");
        jButton_EmpGreta.setEnabled(false);
        jButton_EmpGreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpGretaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_EmpGreta);

        jButton_ControlGreta.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlGreta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlGreta.setText("Simple Contol");
        jButton_ControlGreta.setEnabled(false);
        jButton_ControlGreta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlGretaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlGretaKeyReleased(evt);
            }
        });
        jPanel2.add(jButton_ControlGreta);

        Panel_Agentes6.add(jPanel2);

        jLabel_dirGreta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirGreta.setEnabled(false);
        jLabel_dirGreta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirGretaMouseClicked(evt);
            }
        });
        Panel_Agentes6.add(jLabel_dirGreta);

        jPanel44.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensor Óptico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel44.setLayout(new javax.swing.BoxLayout(jPanel44, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel45.setBackground(new java.awt.Color(197, 197, 197));

        jLabel71.setText("Nada");

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel72)
                .addGap(0, 0, 0))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel44.add(jPanel45);
        jPanel44.add(filler3);

        jPanel46.setBackground(new java.awt.Color(197, 197, 197));

        jLabel73.setText("Obstáculo");

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel74)
                .addGap(0, 0, 0))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel44.add(jPanel46);
        jPanel44.add(filler4);

        jPanel47.setBackground(new java.awt.Color(197, 197, 197));

        jLabel75.setText("Agente");

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel76)
                .addGap(0, 0, 0))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel44.add(jPanel47);

        Panel_Agentes6.add(jPanel44);

        Panel_Agentes4.add(Panel_Agentes6);

        Panel_Agentes7.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Romer", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes7.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes7.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes7.setLayout(new javax.swing.BoxLayout(Panel_Agentes7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpRomer.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpRomer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpRomer.setText("Empezar");
        jButton_EmpRomer.setEnabled(false);
        jButton_EmpRomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpRomerActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_EmpRomer);

        jButton_ControlRomer.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlRomer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlRomer.setText("Simple Contol");
        jButton_ControlRomer.setEnabled(false);
        jButton_ControlRomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlRomerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlRomerKeyReleased(evt);
            }
        });
        jPanel3.add(jButton_ControlRomer);

        Panel_Agentes7.add(jPanel3);

        jLabel_dirRomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirRomer.setEnabled(false);
        jLabel_dirRomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirGretaMouseClicked(evt);
            }
        });
        Panel_Agentes7.add(jLabel_dirRomer);

        jPanel48.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensor Óptico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel48.setLayout(new javax.swing.BoxLayout(jPanel48, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel49.setBackground(new java.awt.Color(197, 197, 197));

        jLabel77.setText("Nada");

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel78)
                .addGap(0, 0, 0))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel48.add(jPanel49);
        jPanel48.add(filler5);

        jPanel50.setBackground(new java.awt.Color(197, 197, 197));

        jLabel79.setText("Obstáculo");

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel80)
                .addGap(0, 0, 0))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel48.add(jPanel50);
        jPanel48.add(filler6);

        jPanel51.setBackground(new java.awt.Color(197, 197, 197));

        jLabel81.setText("Agente");

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel82)
                .addGap(0, 0, 0))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel48.add(jPanel51);

        Panel_Agentes7.add(jPanel48);

        Panel_Agentes4.add(Panel_Agentes7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Agentes4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Agentes3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Agentes4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Agentes3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_conectarRomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarRomerActionPerformed
        gestorConectorRobots(romer,jLabel_connect_romer,jButton_conectarRomer, jButton_ControlRomer);
    }//GEN-LAST:event_jButton_conectarRomerActionPerformed

    private void jButton_conectarFridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarFridaActionPerformed
        gestorConectorRobots(fryda,jLabel_connect_frida,jButton_conectarFrida, jButton_ControlFryda);
    }//GEN-LAST:event_jButton_conectarFridaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        romer.desconectar();
        greta.desconectar();
        fryda.desconectar();
    }//GEN-LAST:event_formWindowClosing

    private void jButton_conectarGretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarGretaActionPerformed
        gestorConectorRobots(greta,jLabel_connect_greta,jButton_conectarGreta, jButton_ControlGreta);       
    }//GEN-LAST:event_jButton_conectarGretaActionPerformed

    private void jButton_ACO_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ACO_ConnectActionPerformed
        
        Tools.GestionLabels.CambiarLabel_esperando25x25( jLabel_ACO_estado );
        
        if( conect_ACO == null || !conect_ACO.isConnected() )
        {
            conect_ACO = new ConexionACO(jTextfield_ACO_host.getText(), Puertos.ACO, 1, new Robot[]{ fryda, romer, greta } );
            conect_ACO.connectTo(jLabel_ACO_estado, jButton_ACO_Connect, jTextfield_ACO_host);
        }
    }//GEN-LAST:event_jButton_ACO_ConnectActionPerformed

    private void jButton_CalibrarSensoresRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalibrarSensoresRobotActionPerformed
        
        Tools.GestionLabels.CambiarLabel_esperando25x25( index.jLabel_calibrarSensoresOpticos );
        
        romer.calibrarSensores();
        fryda.calibrarSensores();
        greta.calibrarSensores();
    }//GEN-LAST:event_jButton_CalibrarSensoresRobotActionPerformed

    private void jLabel_dirFrydaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dirFrydaMouseClicked
        
        if(! jLabel_dirFryda.isEnabled())
            cambiarFlecha();
        
    }//GEN-LAST:event_jLabel_dirFrydaMouseClicked

    private void jLabel_dirGretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dirGretaMouseClicked
        
        if(! jLabel_dirGreta.isEnabled())
            cambiarFlecha();
        
    }//GEN-LAST:event_jLabel_dirGretaMouseClicked

    private void jButton_EmpFrydaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpFrydaActionPerformed
       
        if(fryda.isConnected())
            fryda.start();
        
    }//GEN-LAST:event_jButton_EmpFrydaActionPerformed

    private void jButton_ControlFrydaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlFrydaKeyPressed
      
        if(fryda.isConnected())
        {
            int key = evt.getKeyCode();

            switch (key)
            {
                case KeyEvent.VK_W: //adelante
                    System.out.println("W");
                    fryda.adelante();
                break;

                case KeyEvent.VK_S: //atras
                    fryda.atras();
                break;

                case KeyEvent.VK_A: //izq
                    fryda.izq();
                break;

                case KeyEvent.VK_D: //der
                    fryda.der();
                break;
            }
        }
    }//GEN-LAST:event_jButton_ControlFrydaKeyPressed

    private void jButton_ControlGretaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlGretaKeyPressed
      
        if(greta.isConnected())
        {
            int key = evt.getKeyCode();

            switch (key)
            {
                case KeyEvent.VK_W: //adelante
                    greta.adelante();
                break;

                case KeyEvent.VK_S: //atras
                    greta.atras();
                break;

                case KeyEvent.VK_A: //izq
                    greta.izq();
                break;

                case KeyEvent.VK_D: //der
                    greta.der();
                break;
            }
        }
    }//GEN-LAST:event_jButton_ControlGretaKeyPressed

    private void jButton_ControlRomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlRomerKeyPressed
        
        if(romer.isConnected())
        {
            int key = evt.getKeyCode();

            switch (key)
            {
                case KeyEvent.VK_W: //adelante
                    romer.adelante();
                break;

                case KeyEvent.VK_S: //atras
                    romer.atras();
                break;

                case KeyEvent.VK_A: //izq
                    romer.izq();
                break;

                case KeyEvent.VK_D: //der
                    romer.der();
                break;
            }
        }
    }//GEN-LAST:event_jButton_ControlRomerKeyPressed

    private void jButton_ControlFrydaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlFrydaKeyReleased
        if( fryda.isConnected() )
            fryda.parar();
    }//GEN-LAST:event_jButton_ControlFrydaKeyReleased

    private void jButton_ControlGretaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlGretaKeyReleased
        if( greta.isConnected() )
            greta.parar();
    }//GEN-LAST:event_jButton_ControlGretaKeyReleased

    private void jButton_ControlRomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlRomerKeyReleased
        if( romer.isConnected() )
            romer.parar();
    }//GEN-LAST:event_jButton_ControlRomerKeyReleased

    private void jButton_EmpGretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpGretaActionPerformed
        if(greta.isConnected())
            greta.start();
    }//GEN-LAST:event_jButton_EmpGretaActionPerformed

    private void jButton_EmpRomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpRomerActionPerformed
        if( romer.isConnected() )
            romer.start();
    }//GEN-LAST:event_jButton_EmpRomerActionPerformed

    private void cambiarFlecha()
    {
        fryda.sethorientacion( fryda.gethorientacion()+1 );
        romer.sethorientacion( romer.gethorientacion()+1 );
        greta.sethorientacion( greta.gethorientacion()+1 );
    }
    
    private void gestorConectorRobots( Robot r, JLabel l, JButton b_conectBlueThoot, JButton b_SimpleControl )
    {   
        Tools.GestionLabels.CambiarLabel_esperando25x25(l);
        r.conectar();
        
        if(r.isConnected())
        {
            Tools.GestionLabels.CambiarLabel_correcto25x25(l);
            
            b_conectBlueThoot.setEnabled(false);
            b_SimpleControl.setEnabled(true);
            
            robotsConected++;
            if( robotsConected == 3 )
                jButton_CalibrarSensoresRobot.setEnabled( true );
            
        }
        else
            Tools.GestionLabels.CambiarLabel_incorrecto25x25(l);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Agentes3;
    private javax.swing.JPanel Panel_Agentes4;
    private javax.swing.JPanel Panel_Agentes5;
    private javax.swing.JPanel Panel_Agentes6;
    private javax.swing.JPanel Panel_Agentes7;
    private javax.swing.JLabel Titulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButton_ACO_Connect;
    private javax.swing.JButton jButton_CalibrarSensoresRobot;
    private javax.swing.JButton jButton_ControlFryda;
    private javax.swing.JButton jButton_ControlGreta;
    private javax.swing.JButton jButton_ControlRomer;
    private javax.swing.JButton jButton_EmpFryda;
    private javax.swing.JButton jButton_EmpGreta;
    private javax.swing.JButton jButton_EmpRomer;
    private javax.swing.JButton jButton_conectarFrida;
    private javax.swing.JButton jButton_conectarGreta;
    private javax.swing.JButton jButton_conectarRomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel_ACO_estado;
    public static javax.swing.JLabel jLabel_calibrarSensoresOpticos;
    private javax.swing.JLabel jLabel_connect_VA;
    private javax.swing.JLabel jLabel_connect_frida;
    private javax.swing.JLabel jLabel_connect_greta;
    private javax.swing.JLabel jLabel_connect_romer;
    private javax.swing.JLabel jLabel_dirFryda;
    private javax.swing.JLabel jLabel_dirGreta;
    private javax.swing.JLabel jLabel_dirRomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextfield_ACO_host;
    // End of variables declaration//GEN-END:variables
}
