/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sma;

import Componentes.NXT.Dispositivos;
import Componentes.NXT.Robot;
import Componentes.Pizarra.Pizarra;
import Networking.ConexionACO;
import Networking.ConexionVisionArtificial;
import Networking.base.Puertos;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author diego_juliao
 */
public class index extends javax.swing.JFrame 
{    
    private final ConexionVisionArtificial conect_VA;
    private ConexionACO conect_ACO;
    
    public static Robot romer,greta,fryda;
    public static Robot[] robots;
    private int robotsConected;
    
    public static Pizarra p;
    public static boolean DEBUG = false;

    /**
     * Creates new form index
     */
    public index() 
    {
        initComponents();
        
        JButton buttonsStartRobots[] = { jButton_EmpFryda, jButton_EmpGreta, jButton_EmpRomer };
        
        conect_VA = new ConexionVisionArtificial( jLabel_connect_VA, buttonsStartRobots );

        fryda = new Robot( Dispositivos.Frida, 1, conect_VA, jLabel_dirFryda, jTextField_Fryda_Sonic, jTextField_Fryda_Lumin );
        romer = new Robot( Dispositivos.Romer, 2, conect_VA, jLabel_dirRomer, jTextField_Romer_Sonic, jTextField_Romer_Lumin );
        greta = new Robot( Dispositivos.Greta, 3, conect_VA, jLabel_dirGreta, jTextField_Greta_Sonic, jTextField_Greta_Lumin );
        
        robots = new Robot[3];
        robots[0] = fryda;
        robots[1] = romer;
        robots[2] = greta;
        
        p= new Pizarra(fryda, greta, romer);
        
        robotsConected = 0;
        
        if(DEBUG)
        {
            jButton_EmpFryda.setEnabled(true);
            jButton_EmpRomer.setEnabled(true);
            jButton_EmpGreta.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Panel_Agentes3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_connect_frida = new javax.swing.JLabel();
        jButton_conectarFrida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_connect_romer = new javax.swing.JLabel();
        jButton_conectarRomer = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_connect_greta = new javax.swing.JLabel();
        jButton_conectarGreta = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_calibrarSensoresOpticos = new javax.swing.JLabel();
        jButton_CalibrarSensoresRobot = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_ACO_estado = new javax.swing.JLabel();
        jButton_ACO_Connect = new javax.swing.JButton();
        jTextfield_ACO_host = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel_connect_VA = new javax.swing.JLabel();
        Panel_Agentes4 = new javax.swing.JPanel();
        Panel_Agentes5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_EmpFryda = new javax.swing.JButton();
        jButton_ControlFryda = new javax.swing.JButton();
        jLabel_dirFryda = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jTextField_Fryda_Sonic = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel69 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jTextField_Fryda_Lumin = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel53 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel56 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        Panel_Agentes7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_EmpRomer = new javax.swing.JButton();
        jButton_ControlRomer = new javax.swing.JButton();
        jLabel_dirRomer = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jTextField_Romer_Sonic = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel73 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jTextField_Romer_Lumin = new javax.swing.JTextField();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel31 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel76 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel33 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        Panel_Agentes6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_EmpGreta = new javax.swing.JButton();
        jButton_ControlGreta = new javax.swing.JButton();
        jLabel_dirGreta = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jTextField_Greta_Sonic = new javax.swing.JTextField();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel77 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jTextField_Greta_Lumin = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel36 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel80 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel38 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Droid Sans Mono", 1, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("SMA");
        Titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Panel_Agentes3.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tareas Pendientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes3.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes3.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes3.setLayout(new javax.swing.BoxLayout(Panel_Agentes3, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setText("Conectar Frida(1)");

        jLabel_connect_frida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarFrida.setText("Go");
        jButton_conectarFrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarFridaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton_conectarFrida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_connect_frida)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_frida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarFrida))))
        );

        Panel_Agentes3.add(jPanel6);
        Panel_Agentes3.add(jSeparator1);

        jLabel1.setText("Conectar Romer(2)");

        jLabel_connect_romer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarRomer.setText("Go");
        jButton_conectarRomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarRomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton_conectarRomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_connect_romer)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_romer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarRomer))))
        );

        Panel_Agentes3.add(jPanel5);
        Panel_Agentes3.add(jSeparator6);

        jLabel7.setText("Conectar Greta(3)");

        jLabel_connect_greta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_conectarGreta.setText("Go");
        jButton_conectarGreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_conectarGretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton_conectarGreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_connect_greta)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_connect_greta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_conectarGreta))))
        );

        Panel_Agentes3.add(jPanel7);
        Panel_Agentes3.add(jSeparator5);

        jLabel13.setText("Calibrar Sensores Opticos");

        jLabel_calibrarSensoresOpticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_CalibrarSensoresRobot.setText("Go");
        jButton_CalibrarSensoresRobot.setEnabled(false);
        jButton_CalibrarSensoresRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalibrarSensoresRobotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jButton_CalibrarSensoresRobot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_calibrarSensoresOpticos)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel_calibrarSensoresOpticos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_CalibrarSensoresRobot))))
        );

        Panel_Agentes3.add(jPanel10);
        Panel_Agentes3.add(jSeparator4);

        jLabel19.setText("Conectar ACO");

        jLabel_ACO_estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/sincargar25x25.png"))); // NOI18N

        jButton_ACO_Connect.setText("Go");
        jButton_ACO_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ACO_ConnectActionPerformed(evt);
            }
        });

        jTextfield_ACO_host.setText("127.0.0.1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextfield_ACO_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ACO_Connect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ACO_estado)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ACO_estado)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ACO_Connect)
                        .addComponent(jTextfield_ACO_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Panel_Agentes3.add(jPanel13);
        Panel_Agentes3.add(jSeparator2);

        jLabel21.setText("Conectar Vision Artificial");

        jLabel_connect_VA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/connecting25x25.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel_connect_VA)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_connect_VA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel_Agentes3.add(jPanel14);

        Panel_Agentes4.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agentes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes4.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes4.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes4.setLayout(new javax.swing.BoxLayout(Panel_Agentes4, javax.swing.BoxLayout.PAGE_AXIS));

        Panel_Agentes5.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fryda(1)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes5.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes5.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes5.setLayout(new javax.swing.BoxLayout(Panel_Agentes5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpFryda.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpFryda.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpFryda.setText("Empezar");
        jButton_EmpFryda.setEnabled(false);
        jButton_EmpFryda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpFrydaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EmpFryda);

        jButton_ControlFryda.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlFryda.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlFryda.setText("Simple Contol");
        jButton_ControlFryda.setEnabled(false);
        jButton_ControlFryda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlFrydaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlFrydaKeyReleased(evt);
            }
        });
        jPanel1.add(jButton_ControlFryda);

        Panel_Agentes5.add(jPanel1);

        jLabel_dirFryda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirFryda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_dirFryda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirFrydaMouseClicked(evt);
            }
        });
        Panel_Agentes5.add(jLabel_dirFryda);

        jPanel42.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel42.setLayout(new javax.swing.BoxLayout(jPanel42, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel44.setBackground(new java.awt.Color(197, 197, 197));

        jLabel69.setText("Sónico");

        jTextField_Fryda_Sonic.setEditable(false);
        jTextField_Fryda_Sonic.setText("255");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Fryda_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Fryda_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)))
        );

        jPanel12.add(jPanel44);
        jPanel12.add(filler5);

        jPanel69.setBackground(new java.awt.Color(197, 197, 197));

        jLabel99.setText("Lumínico");

        jTextField_Fryda_Lumin.setEditable(false);
        jTextField_Fryda_Lumin.setText("255");

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel99)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Fryda_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel69Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel99)
                    .addComponent(jTextField_Fryda_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel12.add(jPanel69);

        jPanel42.add(jPanel12);
        jPanel42.add(filler3);

        jPanel53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel53.setLayout(new javax.swing.BoxLayout(jPanel53, javax.swing.BoxLayout.LINE_AXIS));

        jPanel55.setBackground(new java.awt.Color(197, 197, 197));
        jPanel55.setLayout(new javax.swing.BoxLayout(jPanel55, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBackground(new java.awt.Color(197, 197, 197));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel87.setText("Obstáculo");
        jPanel4.add(jLabel87);

        jPanel55.add(jPanel4);
        jPanel55.add(jSeparator7);

        jPanel8.setBackground(new java.awt.Color(197, 197, 197));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel8.add(jLabel88);

        jPanel55.add(jPanel8);

        jPanel53.add(jPanel55);
        jPanel53.add(filler1);

        jPanel56.setBackground(new java.awt.Color(197, 197, 197));
        jPanel56.setLayout(new javax.swing.BoxLayout(jPanel56, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setBackground(new java.awt.Color(197, 197, 197));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel89.setText("Agente");
        jPanel9.add(jLabel89);

        jPanel56.add(jPanel9);
        jPanel56.add(jSeparator8);

        jPanel11.setBackground(new java.awt.Color(197, 197, 197));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel11.add(jLabel90);

        jPanel56.add(jPanel11);

        jPanel53.add(jPanel56);

        jPanel42.add(jPanel53);

        Panel_Agentes5.add(jPanel42);

        Panel_Agentes4.add(Panel_Agentes5);

        Panel_Agentes7.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Romer(2)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes7.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes7.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes7.setLayout(new javax.swing.BoxLayout(Panel_Agentes7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpRomer.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpRomer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpRomer.setText("Empezar");
        jButton_EmpRomer.setEnabled(false);
        jButton_EmpRomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpRomerActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_EmpRomer);

        jButton_ControlRomer.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlRomer.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlRomer.setText("Simple Contol");
        jButton_ControlRomer.setEnabled(false);
        jButton_ControlRomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlRomerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlRomerKeyReleased(evt);
            }
        });
        jPanel3.add(jButton_ControlRomer);

        Panel_Agentes7.add(jPanel3);

        jLabel_dirRomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirRomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirRomerMouseClicked(evt);
            }
        });
        Panel_Agentes7.add(jLabel_dirRomer);

        jPanel46.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel46.setLayout(new javax.swing.BoxLayout(jPanel46, javax.swing.BoxLayout.LINE_AXIS));

        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel47.setBackground(new java.awt.Color(197, 197, 197));

        jLabel71.setText("Sónico");

        jTextField_Romer_Sonic.setEditable(false);
        jTextField_Romer_Sonic.setText("255");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Romer_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Romer_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71)))
        );

        jPanel29.add(jPanel47);
        jPanel29.add(filler8);

        jPanel73.setBackground(new java.awt.Color(197, 197, 197));

        jLabel105.setText("Lumínico");

        jTextField_Romer_Lumin.setEditable(false);
        jTextField_Romer_Lumin.setText("255");

        javax.swing.GroupLayout jPanel73Layout = new javax.swing.GroupLayout(jPanel73);
        jPanel73.setLayout(jPanel73Layout);
        jPanel73Layout.setHorizontalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel105)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Romer_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel73Layout.setVerticalGroup(
            jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel73Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel105)
                    .addComponent(jTextField_Romer_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel29.add(jPanel73);

        jPanel46.add(jPanel29);
        jPanel46.add(filler9);

        jPanel74.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel74.setLayout(new javax.swing.BoxLayout(jPanel74, javax.swing.BoxLayout.LINE_AXIS));

        jPanel75.setBackground(new java.awt.Color(197, 197, 197));
        jPanel75.setLayout(new javax.swing.BoxLayout(jPanel75, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel30.setBackground(new java.awt.Color(197, 197, 197));
        jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel106.setText("Obstáculo");
        jPanel30.add(jLabel106);

        jPanel75.add(jPanel30);
        jPanel75.add(jSeparator11);

        jPanel31.setBackground(new java.awt.Color(197, 197, 197));
        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel31.add(jLabel107);

        jPanel75.add(jPanel31);

        jPanel74.add(jPanel75);
        jPanel74.add(filler15);

        jPanel76.setBackground(new java.awt.Color(197, 197, 197));
        jPanel76.setLayout(new javax.swing.BoxLayout(jPanel76, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel32.setBackground(new java.awt.Color(197, 197, 197));
        jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel108.setText("Agente");
        jPanel32.add(jLabel108);

        jPanel76.add(jPanel32);
        jPanel76.add(jSeparator12);

        jPanel33.setBackground(new java.awt.Color(197, 197, 197));
        jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel33.add(jLabel109);

        jPanel76.add(jPanel33);

        jPanel74.add(jPanel76);

        jPanel46.add(jPanel74);

        Panel_Agentes7.add(jPanel46);

        Panel_Agentes4.add(Panel_Agentes7);

        Panel_Agentes6.setBackground(new java.awt.Color(197, 197, 197));
        Panel_Agentes6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Greta(3)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Andale Mono", 0, 14), new java.awt.Color(1, 1, 1))); // NOI18N
        Panel_Agentes6.setForeground(new java.awt.Color(1, 1, 1));
        Panel_Agentes6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel_Agentes6.setPreferredSize(new java.awt.Dimension(666, 666));
        Panel_Agentes6.setLayout(new javax.swing.BoxLayout(Panel_Agentes6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton_EmpGreta.setBackground(new java.awt.Color(72, 151, 1));
        jButton_EmpGreta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_EmpGreta.setText("Empezar");
        jButton_EmpGreta.setEnabled(false);
        jButton_EmpGreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EmpGretaActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_EmpGreta);

        jButton_ControlGreta.setBackground(new java.awt.Color(118, 118, 118));
        jButton_ControlGreta.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ControlGreta.setText("Simple Contol");
        jButton_ControlGreta.setEnabled(false);
        jButton_ControlGreta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ControlGretaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton_ControlGretaKeyReleased(evt);
            }
        });
        jPanel2.add(jButton_ControlGreta);

        Panel_Agentes6.add(jPanel2);

        jLabel_dirGreta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Direcciones/0.png"))); // NOI18N
        jLabel_dirGreta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dirGretaMouseClicked(evt);
            }
        });
        Panel_Agentes6.add(jLabel_dirGreta);

        jPanel48.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sensores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel48.setLayout(new javax.swing.BoxLayout(jPanel48, javax.swing.BoxLayout.LINE_AXIS));

        jPanel34.setLayout(new javax.swing.BoxLayout(jPanel34, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel49.setBackground(new java.awt.Color(197, 197, 197));

        jLabel72.setText("Sónico");

        jTextField_Greta_Sonic.setEditable(false);
        jTextField_Greta_Sonic.setText("255");

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Greta_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Greta_Sonic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72)))
        );

        jPanel34.add(jPanel49);
        jPanel34.add(filler16);

        jPanel77.setBackground(new java.awt.Color(197, 197, 197));

        jLabel110.setText("Lumínico");

        jTextField_Greta_Lumin.setEditable(false);
        jTextField_Greta_Lumin.setText("255");

        javax.swing.GroupLayout jPanel77Layout = new javax.swing.GroupLayout(jPanel77);
        jPanel77.setLayout(jPanel77Layout);
        jPanel77Layout.setHorizontalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel77Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel110)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Greta_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel77Layout.setVerticalGroup(
            jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel77Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(jTextField_Greta_Lumin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel34.add(jPanel77);

        jPanel48.add(jPanel34);
        jPanel48.add(filler17);

        jPanel78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel78.setLayout(new javax.swing.BoxLayout(jPanel78, javax.swing.BoxLayout.LINE_AXIS));

        jPanel79.setBackground(new java.awt.Color(197, 197, 197));
        jPanel79.setLayout(new javax.swing.BoxLayout(jPanel79, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel35.setBackground(new java.awt.Color(197, 197, 197));
        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel111.setText("Obstáculo");
        jPanel35.add(jLabel111);

        jPanel79.add(jPanel35);
        jPanel79.add(jSeparator13);

        jPanel36.setBackground(new java.awt.Color(197, 197, 197));
        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel36.add(jLabel112);

        jPanel79.add(jPanel36);

        jPanel78.add(jPanel79);
        jPanel78.add(filler18);

        jPanel80.setBackground(new java.awt.Color(197, 197, 197));
        jPanel80.setLayout(new javax.swing.BoxLayout(jPanel80, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel37.setBackground(new java.awt.Color(197, 197, 197));
        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel113.setText("Agente");
        jPanel37.add(jLabel113);

        jPanel80.add(jPanel37);
        jPanel80.add(jSeparator14);

        jPanel38.setBackground(new java.awt.Color(197, 197, 197));
        jPanel38.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Img/Pblack.png"))); // NOI18N
        jPanel38.add(jLabel114);

        jPanel80.add(jPanel38);

        jPanel78.add(jPanel80);

        jPanel48.add(jPanel78);

        Panel_Agentes6.add(jPanel48);

        Panel_Agentes4.add(Panel_Agentes6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Agentes4, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Agentes3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Agentes3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Agentes4, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_conectarRomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarRomerActionPerformed
        gestorConectorRobots(romer,jLabel_connect_romer,jButton_conectarRomer, jButton_ControlRomer);
    }//GEN-LAST:event_jButton_conectarRomerActionPerformed

    private void jButton_conectarFridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarFridaActionPerformed
        gestorConectorRobots(fryda,jLabel_connect_frida,jButton_conectarFrida, jButton_ControlFryda);
    }//GEN-LAST:event_jButton_conectarFridaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        romer.desconectar();
        greta.desconectar();
        fryda.desconectar();
    }//GEN-LAST:event_formWindowClosing

    private void jButton_conectarGretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_conectarGretaActionPerformed
        gestorConectorRobots(greta,jLabel_connect_greta,jButton_conectarGreta, jButton_ControlGreta);       
    }//GEN-LAST:event_jButton_conectarGretaActionPerformed

    private void jButton_ACO_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ACO_ConnectActionPerformed
        
        Tools.GestionLabels.CambiarLabel_esperando25x25( jLabel_ACO_estado );
        
        if( conect_ACO == null || !conect_ACO.isConnected() )
        {
            conect_ACO = new ConexionACO(jTextfield_ACO_host.getText(), Puertos.ACO, new Robot[]{ fryda, romer, greta } );
            conect_ACO.connectTo(jLabel_ACO_estado, jButton_ACO_Connect, jTextfield_ACO_host);
            
            for (Robot robot : robots)
                robot.setConect_ACO(conect_ACO);            
        }
    }//GEN-LAST:event_jButton_ACO_ConnectActionPerformed

    private void jButton_CalibrarSensoresRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalibrarSensoresRobotActionPerformed
        
        Tools.GestionLabels.CambiarLabel_esperando25x25( index.jLabel_calibrarSensoresOpticos );
        
        romer.calibrarSensores();
        fryda.calibrarSensores();
        greta.calibrarSensores();
        
    }//GEN-LAST:event_jButton_CalibrarSensoresRobotActionPerformed

    private void jLabel_dirGretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dirGretaMouseClicked
        
        if( jLabel_dirGreta.isEnabled())
            cambiarFlecha();
        
    }//GEN-LAST:event_jLabel_dirGretaMouseClicked

    private void jButton_ControlGretaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlGretaKeyPressed
        manejarRobot(greta, evt);
    }//GEN-LAST:event_jButton_ControlGretaKeyPressed

    private void jButton_ControlRomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlRomerKeyPressed
        manejarRobot(romer, evt);
    }//GEN-LAST:event_jButton_ControlRomerKeyPressed

    private void manejarRobot(Robot r, java.awt.event.KeyEvent evt)
    {
        if(r.isConnected())
        {
            int key = evt.getKeyCode();
            
            switch (key)
            {
                case KeyEvent.VK_W: //adelante
                    r.adelante();
                break;

                case KeyEvent.VK_S: //atras
                    r.atras();
                break;

                case KeyEvent.VK_A: //izq
                    r.izq();
                break;

                case KeyEvent.VK_D: //der
                    r.der();
                break;
            }
        }
    }
    
    private void jButton_ControlGretaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlGretaKeyReleased
        if( greta.isConnected() )
            greta.parar();
    }//GEN-LAST:event_jButton_ControlGretaKeyReleased

    private void jButton_ControlRomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlRomerKeyReleased
        if( romer.isConnected() )
            romer.parar();
    }//GEN-LAST:event_jButton_ControlRomerKeyReleased

    private void jButton_EmpGretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpGretaActionPerformed
        robotStart(greta);
    }//GEN-LAST:event_jButton_EmpGretaActionPerformed

    private void jButton_EmpRomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpRomerActionPerformed
        robotStart(romer);
    }//GEN-LAST:event_jButton_EmpRomerActionPerformed

    private void jLabel_dirRomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dirRomerMouseClicked
         if( jLabel_dirRomer.isEnabled())
            cambiarFlecha();
    }//GEN-LAST:event_jLabel_dirRomerMouseClicked

    private void jLabel_dirFrydaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dirFrydaMouseClicked

        if( jLabel_dirFryda.isEnabled())
        cambiarFlecha();

    }//GEN-LAST:event_jLabel_dirFrydaMouseClicked

    private void jButton_ControlFrydaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlFrydaKeyReleased
        if( fryda.isConnected() )
        fryda.parar();
    }//GEN-LAST:event_jButton_ControlFrydaKeyReleased

    private void jButton_ControlFrydaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ControlFrydaKeyPressed
        manejarRobot(fryda, evt);
    }//GEN-LAST:event_jButton_ControlFrydaKeyPressed

    private void jButton_EmpFrydaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EmpFrydaActionPerformed

        robotStart(fryda);
    }//GEN-LAST:event_jButton_EmpFrydaActionPerformed

    private void robotStart( Robot r )
    {
        if( r.isConnected() )
        {
            if( !r.isAlive() )
                r.start();
            else
                r.continuarHilo();
        }
    }
    
    private void cambiarFlecha()
    {
        fryda.setSiguiente_horientacion();
        romer.setSiguiente_horientacion();
        greta.setSiguiente_horientacion();
    }
    
    private void gestorConectorRobots( Robot r, JLabel l, JButton b_conectBlueThoot, JButton b_SimpleControl )
    {   
        Tools.GestionLabels.CambiarLabel_esperando25x25(l);
        r.conectar();
        
        if(r.isConnected())
        {
            Tools.GestionLabels.CambiarLabel_correcto25x25(l);
            
            b_conectBlueThoot.setEnabled(false);
            b_SimpleControl.setEnabled(true);
            
            robotsConected++;
            if( robotsConected == 3 )
                jButton_CalibrarSensoresRobot.setEnabled( true );
            
        }
        else
            Tools.GestionLabels.CambiarLabel_incorrecto25x25(l);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    
    private boolean todoListo()
    {
        if( ((romer.isConnected() && fryda.isConnected() && greta.isConnected() )  ||  DEBUG) && //que todos los robots estén conectados o que se esté en modo DEBUG
            conect_VA.isConnected() && //que se esté conectado con la visión artificial
            (conect_ACO.isConnected() || DEBUG) &&//que se esté conectado con ACO o se esté e modo DEBUG
            (( romer.isCalibratedLigth() && fryda.isCalibratedLigth() && greta.isCalibratedLigth() )  ||  DEBUG ) //todos los sensores calibrados o se esté en modo debug
          )
            return true;
        else
            return false;
                    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Agentes3;
    private javax.swing.JPanel Panel_Agentes4;
    private javax.swing.JPanel Panel_Agentes5;
    private javax.swing.JPanel Panel_Agentes6;
    private javax.swing.JPanel Panel_Agentes7;
    private javax.swing.JLabel Titulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton_ACO_Connect;
    private javax.swing.JButton jButton_CalibrarSensoresRobot;
    private javax.swing.JButton jButton_ControlFryda;
    private javax.swing.JButton jButton_ControlGreta;
    private javax.swing.JButton jButton_ControlRomer;
    private javax.swing.JButton jButton_EmpFryda;
    private javax.swing.JButton jButton_EmpGreta;
    private javax.swing.JButton jButton_EmpRomer;
    private javax.swing.JButton jButton_conectarFrida;
    private javax.swing.JButton jButton_conectarGreta;
    private javax.swing.JButton jButton_conectarRomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel jLabel_ACO_estado;
    public static javax.swing.JLabel jLabel_calibrarSensoresOpticos;
    private javax.swing.JLabel jLabel_connect_VA;
    private javax.swing.JLabel jLabel_connect_frida;
    private javax.swing.JLabel jLabel_connect_greta;
    private javax.swing.JLabel jLabel_connect_romer;
    private javax.swing.JLabel jLabel_dirFryda;
    private javax.swing.JLabel jLabel_dirGreta;
    private javax.swing.JLabel jLabel_dirRomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField_Fryda_Lumin;
    private javax.swing.JTextField jTextField_Fryda_Sonic;
    private javax.swing.JTextField jTextField_Greta_Lumin;
    private javax.swing.JTextField jTextField_Greta_Sonic;
    private javax.swing.JTextField jTextField_Romer_Lumin;
    private javax.swing.JTextField jTextField_Romer_Sonic;
    private javax.swing.JTextField jTextfield_ACO_host;
    // End of variables declaration//GEN-END:variables
}
